Revert "Handle non-base-10 compat_props on level/xlevel fixup code"
This reverts commit a75e9b46e32c47a1b8451ad3279f1747fbf4cd47.

The commit causes this crash:

Traceback (most recent call last):
  File "./compat_checker.py", line 1162, in <module>
    sys.exit(main())
  File "./compat_checker.py", line 1159, in main
    compare_binaries(args, ctx)
  File "./compat_checker.py", line 1076, in compare_binaries
    compare_machine(args, mctx)
  File "./compat_checker.py", line 1061, in compare_machine
    compare_machine_compat_props(args, ctx, m1, m2)
  File "./compat_checker.py", line 824, in compare_machine_compat_props
    pi1, v1 = calculate_prop_value(ctx.b1_ctx(), compat1, d, p)
  File "./compat_checker.py", line 793, in calculate_prop_value
    v = fixup_prop_value(ctx, compat, devtype, propname, v)
  File "./compat_checker.py", line 739, in fixup_prop_value
    return calculate_prop_value(ctx, compat, devtype, lprop)[1]
  File "./compat_checker.py", line 793, in calculate_prop_value
    v = fixup_prop_value(ctx, compat, devtype, propname, v)
  File "./compat_checker.py", line 735, in fixup_prop_value
    return int(v, base=0) & 0xFFFFFFFF
TypeError: int() can't convert non-string with explicit base

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>